version: "3.5"
services:
  machine_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: machine_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: db
      MYSQL_DATABASE: slim
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - 3306:3306

  machine_api:
    build:
      context: .
    command: php -S 0.0.0.0:8080 -t public
    container_name: machine_api
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/
    depends_on:
      - machine_mysql
